version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80/tcp"
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure